import { chromium } from 'playwright-core';
import { spawn } from 'node:child_process';
const srv = spawn('npx', ['vite', 'preview', '--port', '4174', '--strictPort'], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 2500));
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:4174/');
await p.screenshot({ path: process.argv[3] + '/vacio.png', fullPage: true });
await p.getByRole('button', { name: /^Datos/ }).click();
await p.locator('input[type=file]').first().setInputFiles(process.argv[2]);
await p.waitForTimeout(600);
await p.screenshot({ path: process.argv[3] + '/import.png', fullPage: true });
await p.getByRole('button', { name: /^Importar 2 filas/ }).click();
await p.getByRole('button', { name: /^Ads/ }).click();
await p.waitForTimeout(300);
console.log((await p.locator('.stat .v').first().textContent()), errs.join('|') || 'sin errores');
await p.reload();
await p.getByRole('button', { name: /^Ads/ }).click();
console.log('tras recargar:', await p.locator('.stat .v').first().textContent());
await b.close(); srv.kill();
